
module.exports = {
  //USERS
  CREATE_USER : 'CREATE_USER',
  INIT_USERS : 'INIT_USERS',
  UPDATE_USER: 'UPDATE_USER',
  //LOGIN
  LOGIN_SUCCESS : 'LOGIN_SUCCESS',
  LOGIN_FAILED : 'LOGIN_FAILED',
  LOG_OFF: 'LOG_OFF',
  LOGIN_UPDATE: 'LOGIN_UPDATE',
  //UI
  CHANGE_COLOR: 'CHANGE_COLOR',
  //CATEGORIES
  INIT_CATEGORIES: 'INIT_CATEGORIES',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  //ITEMS
  INIT_ITEMS: 'INIT_ITEMS',
  CREATE_ITEM: 'CREATE_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  VOTE_ITEM: 'VOTE_ITEM',
  DEVOTE_ITEM: 'DEVOTE_ITEM',
  //POSTS
  INIT_POSTS: 'INIT_POSTS',
  ADD_POST: 'ADD_POST',
  DELETE_POST: 'DELETE_POST',
}
